'''
'''
UNDEFINED = UNDEFINED_FLOAT
NODATA_FLOAT = UNDEFINED_FLOAT
NODATA_DOUBLE = UNDEFINED_DOUBLE
NODATA_TIME = UNDEFINED_TIME
NODATA_NEGATIVE = -9999
HRAP_DATASOURCE = HRAP_SRC_DEFINITION
SHG_DATASOURCE = SHG_SRC_DEFINITION
UTM_DATASOURCE = UTM_SRC_DEFINITION

# testing enum
cpdef enum:
    A = 25
    B = 30
