'''
'''
UNDEFINED = UNDEFINED_FLOAT
NODATA_FLOAT = UNDEFINED_FLOAT
NODATA_DOUBLE = UNDEFINED_DOUBLE
NODATA_TIME = UNDEFINED_TIME
NODATA_NEGATIVE = -9999
HRAP_WKT = HRAP_SRC_DEFINITION
SHG_WKT = SHG_SRC_DEFINITION
UTM_WKT = UTM_SRC_DEFINITION
