name: OptB - Windows (Intel oneAPI HPC) & Linux (gfortran) wheels + publish [ci_tests only]

on:
  push:
    branches: [ ci_tests ]
  pull_request:
    branches: [ ci_tests ]
  workflow_dispatch:
    inputs:
      target:
        description: "Publish target"
        required: false
        default: ""
        type: choice
        options:
          - ""        # build only
          - testpypi
          - pypi

jobs:
  build-wheels:
    name: Build wheels (${{ matrix.os }})
    if: startsWith(github.ref, 'refs/heads/ci_tests')
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, ubuntu-22.04]

    env:
      # Build these CPython versions
      CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-*"
      CIBW_SKIP: "pp* *-win32 *-musllinux_*"
      CIBW_ARCHS_WINDOWS: "AMD64"
      CIBW_ARCHS_LINUX: "x86_64"

      # Import check after each wheel is built
      CIBW_TEST_COMMAND: >
        python -c "import pydsstools, sys; print('OK', sys.version, getattr(pydsstools,'__version__','?'))"

      # Use manylinux2014 unless you require newer glibc
      CIBW_MANYLINUX_X86_64_IMAGE: "manylinux2014"

      # Inside the manylinux container, install gfortran & headers
      CIBW_BEFORE_ALL_LINUX: >
        yum -y install gcc gcc-c++ gcc-gfortran zlib-devel libstdc++-devel &&
        echo "Installed gcc/gfortran and headers in manylinux"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # Host Python to drive cibuildwheel (not the versions being built)
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # ----- Windows: Install Intel oneAPI Fortran (HPC/classic: ifort) -----
      - name: Setup Intel Fortran (Windows)
      # Only on Windows runners
        if: startsWith(matrix.os, 'windows-')
        uses: fortran-lang/setup-fortran@v1
        with:
          compiler: intel-classic   # ifort (classic). Use `intel` for ifx (LLVM)

      - name: Show toolchain (Windows)
        if: startsWith(matrix.os, 'windows-')
        shell: cmd
        run: |
          where ifort || ver
          where ifx   || ver
          where cl    || ver

      - name: Upgrade build tooling
        run: |
          python -m pip install -U pip wheel setuptools build
          python -m pip install -U cibuildwheel==2.*

      # Build wheels (both OSes). On Windows we set FC to Intel Fortran.
      - name: Build wheels (Windows)
        if: startsWith(matrix.os, 'windows-')
        shell: cmd
        env:
          CIBW_ENVIRONMENT_WINDOWS: "FC=ifort"
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - name: Build wheels (Linux)
        if: startsWith(matrix.os, 'ubuntu-')
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      # Build sdist (identical on both; last one wins)
      - name: Build sdist
        run: |
          python -m build --sdist

      - name: Collect artifacts
        shell: bash
        run: |
          mkdir -p dist
          cp -v wheelhouse/*.whl dist/
          cp -v dist/*.tar.gz dist/ 2>/dev/null || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: dist/*

  publish:
    name: Publish to (Test)PyPI
    needs: [build-wheels]
    # Only allow publish when manually dispatched AND ref is ci_tests
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/ci_tests'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          merge-multiple: true
          path: dist

      - name: Choose repository URL
        id: repo
        run: |
          if [ "${{ github.event.inputs.target }}" = "testpypi" ]; then
            echo "url=https://test.pypi.org/legacy/" >> $GITHUB_OUTPUT
            echo "token_name=TEST_PYPI_API_TOKEN" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.inputs.target }}" = "pypi" ]; then
            echo "url=https://upload.pypi.org/legacy/" >> $GITHUB_OUTPUT
            echo "token_name=PYPI_API_TOKEN" >> $GITHUB_OUTPUT
          else
            echo "url=" >> $GITHUB_OUTPUT
            echo "token_name=" >> $GITHUB_OUTPUT
          fi

      - name: Publish (pypa/gh-action-pypi-publish)
        if: steps.repo.outputs.url != ''
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: ${{ steps.repo.outputs.url }}
          password: ${{ secrets[steps.repo.outputs.token_name] }}
          packages-dir: dist
          skip-existing: true